<a href="https://colab.research.google.com/github/Shivam4988/Assignment/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. What is a Python library? Why do we use Python libraries?
A Python library is a collection of pre-written functions and modules that extend Python's capabilities. We use libraries to avoid reinventing the wheel, improve efficiency, and leverage optimized code for complex tasks (e.g., Numpy for numerical computations).

### 2. What is the difference between Numpy array and List?

Numpy Array: Homogeneous (all elements same type), stored in contiguous memory, optimized for numerical operations.

List: Heterogeneous (elements can be different types), flexible but slower for large datasets.

### 3. Find the shape, size, and dimension of the following array?
Given a 3x4 array:

Shape: (3, 4)

Size: 12 (total elements)

Dimension: 2 (2D array).

### 4. Write Python code to access the first row of the array?

In [1]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
first_row = arr[0]  # Output: [1 2 3 4]

### 5. How do you access the element at the third row and fourth column?

In [2]:
element = arr[2, 3]  # Output: 12

### 6. Write code to extract all odd-indexed elements from the array?
Assuming "odd-indexed" refers to indices starting at 1 (0-based):

In [3]:
odd_indexed = arr[:, 1::2]  # Columns 1 and 3 (indices 1 and 3)
# Output:
# [[ 2  4]
#  [ 6  8]
#  [10 12]]

### 7. How to generate a random 3x3 matrix with values between 0 and 1?

In [4]:
random_matrix = np.random.rand(3, 3)

### 8. Difference between np.random.rand and np.random.randn?

rand: Uniform distribution over [0, 1).

randn: Standard normal distribution (mean=0, variance=1).

### 9. Write code to increase the dimension of the array?
Add a new axis to convert from 3x4 to 1x3x4:

In [5]:
higher_dim = arr[np.newaxis, :]  # or np.expand_dims(arr, axis=0)

### 10. How to transpose the array in Numpy?

In [6]:
transposed = arr.T  # or np.transpose(arr)
# Output:
# [[ 1  5  9]
#  [ 2  6 10]
#  [ 3  7 11]
#  [ 4  8 12]]

### 11. Perform operations on Matrix A and B (both 3x4):

**Given Matrices:**

In [9]:
import numpy as np

A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

1. Element-wise multiplication:

In [10]:
element_wise = A * B
# Output:
# [[  1   4   9  16]
#  [ 25  36  49  64]
#  [ 81 100 121 144]]

2. Matrix multiplication:

Since matrices are 3x4, transpose B to make it 4x3:

In [11]:
matrix_mul = np.dot(A, B.T)  # Result shape: 3x3
# Output:
# [[ 30  70 110]
#  [ 70 174 278]
#  [110 278 446]]

3. Add both matrices:

In [12]:
matrix_add = A + B
# Output:
# [[ 2  4  6  8]
#  [10 12 14 16]
#  [18 20 22 24]]

4. Subtract matrix B from A:

In [13]:
matrix_sub = A - B
# Output (all zeros since A and B are identical):
# [[0 0 0 0]
#  [0 0 0 0]
#  [0 0 0 0]]

5. Divide matrix B by A:

In [14]:
matrix_div = B / A
# Output (all ones since A and B are identical):
# [[1. 1. 1. 1.]
#  [1. 1. 1. 1.]
#  [1. 1. 1. 1.]]

### 12. Function to swap byte order of an array?
Use numpy.ndarray.byteswap().

### 13. Significance of np.iindg.inv?
Typo correction: The correct function is np.linalg.inv. It computes the multiplicative inverse of a square matrix.

### 14. What does np.reshape do?
Reshapes an array to a new shape without changing data:

In [15]:
reshaped = arr.reshape(4, 3)  # Converts 3x4 to 4x3

### 15. What is broadcasting in Numpy?
Broadcasting allows operations on arrays of different shapes by automatically expanding smaller arrays to match larger ones, following specific rules (e.g., scalar + array, or adding 3x1 and 1x3 arrays).